document.write('<script type="text/javascript" src="js/accordion.js"></script>');
document.write('<script type="text/javascript" src="js/ajax.js"></script>');
document.write('<script type="text/javascript" src="js/submitBtn.js"></script>');
document.write('<script type="text/javascript" src="js/alert.js"></script>');
document.write('<script type="text/javascript" src="js/scroll-top.js"></script>');
document.write('<script type="text/javascript" src="js/matchHeight.js"></script>');
document.write('<script type="text/javascript" src="js/accordionFlow.js"></script>');
// document.write('<script type="text/javascript" src="js/carousel.js"></script>');
// document.write('<script type="text/javascript" src="js/swiper.js"></script>');
// document.write('<script type="text/javascript" src="js/hamburger.js"></script>');
// document.write('<script type="text/javascript" src="js/aos.js"></script>');
